import type { Era, HistoricalTeam, RosterSlotTemplate } from './types';

// ─── Sport Config (NBA only) ─────────────────────────────────────────────────

export const SPORT_CONFIG = {
  label: 'NBA',
  emoji: '🏀',
  primaryColor: '#F26522',
  accentColor: '#FDB927',
  bgColor: '#1a0f00',
  gamesInSeason: 82,
  tagline: 'Can your squad go 82-0?',
} as const;

// ─── Roster Template ─────────────────────────────────────────────────────────
//   PG · SG · SF · PF · C · 6th Man (flex)

export const NBA_ROSTER: RosterSlotTemplate[] = [
  { id: 'pg',   position: 'PG',                        label: 'Point Guard',    group: 'offense', required: true },
  { id: 'sg',   position: 'SG',                        label: 'Shooting Guard', group: 'offense', required: true },
  { id: 'sf',   position: 'SF',                        label: 'Small Forward',  group: 'offense', required: true },
  { id: 'pf',   position: 'PF',                        label: 'Power Forward',  group: 'offense', required: true },
  { id: 'c',    position: 'C',                         label: 'Center',         group: 'offense', required: true },
  { id: '6man', position: ['PG','SG','SF','PF','C'],   label: '6th Man',        group: 'offense', required: true },
];

// ─── GSPR Tiers ───────────────────────────────────────────────────────────────

export const GSPR_TIERS = [
  { min: 950, label: 'GOD SQUAD', color: '#ff4444', glow: 'rgba(255,68,68,0.5)' },
  { min: 850, label: 'LEGENDARY', color: '#ffd700', glow: 'rgba(255,215,0,0.4)' },
  { min: 700, label: 'GREAT',     color: '#a855f7', glow: 'rgba(168,85,247,0.3)' },
  { min: 500, label: 'GOOD',      color: '#3b82f6', glow: 'rgba(59,130,246,0.3)' },
  { min: 0,   label: 'AVERAGE',   color: '#6b7280', glow: 'rgba(107,114,128,0.2)' },
];

export function getGsprTier(gspr: number) {
  return GSPR_TIERS.find(t => gspr >= t.min) ?? GSPR_TIERS[GSPR_TIERS.length - 1];
}

// ─── Era generation ───────────────────────────────────────────────────────────

const NBA_ERA_START = 1970;

const TEAM_FOUNDED: Partial<Record<string, number>> = {
  'nba-4':  1988,  // Charlotte
  'nba-7':  1980,  // Dallas
  'nba-15': 1995,  // Toronto
  'nba-16': 1988,  // Miami
  'nba-18': 1989,  // Orlando
  'nba-19': 2002,  // New Orleans
  'nba-22': 1989,  // Minnesota
  'nba-28': 1995,  // Toronto (was set, keep)
  'nba-30': 1995,  // Oklahoma (was SEA)
};

// Keys must match the era IDs generated by generateTeamEras — 5-year boundaries only.
// Format: nba-{teamId}-{startYear}, where startYear is a multiple of 5 (1970, 1975, 1980 …)
const ERA_DATA: Record<string, { name: string; description: string }> = {
  // ── Lakers ──────────────────────────────────────────────────────────────────
  'nba-14-1980': { name: 'Showtime I',       description: "Magic Johnson's no-look passes ignite Showtime; two titles in five years with Kareem" },
  'nba-14-1985': { name: 'Showtime II',      description: "Back-to-back titles cap the Showtime era; Kareem and Magic are unstoppable together" },
  'nba-14-2000': { name: 'Shaq & Kobe',      description: "Shaquille O'Neal and Kobe Bryant rip off three straight championships" },
  'nba-14-2005': { name: "Kobe & Gasol",     description: "Kobe Bryant and Pau Gasol win back-to-back rings in 2009 and 2010" },
  // ── Celtics ─────────────────────────────────────────────────────────────────
  'nba-2-1980':  { name: 'Bird Era I',       description: "Larry Bird, Kevin McHale, and Robert Parish deliver three championships" },
  'nba-2-1985':  { name: 'Bird Era II',      description: "Bird at peak powers one final title run; McHale and Walton provide the depth" },
  'nba-2-2005':  { name: 'Big Three Revival',description: "Paul Pierce, Kevin Garnett, and Ray Allen assemble to end the drought" },
  'nba-2-2010':  { name: 'Banner 18 Hunt',   description: "The Big Three chase another title; Rondo emerges as a Finals-level point guard" },
  // ── Bulls ───────────────────────────────────────────────────────────────────
  'nba-5-1990':  { name: 'First Three-Peat', description: "Michael Jordan and Scottie Pippen win three straight titles with the Triangle Offense" },
  'nba-5-1995':  { name: 'Second Three-Peat',description: "Jordan returns, Rodman joins, and Chicago wins three more rings" },
  'nba-5-2010':  { name: 'Derrick Rose Era', description: "Derrick Rose wins MVP at 22; the Bulls build the East's most feared defense" },
  // ── Spurs ───────────────────────────────────────────────────────────────────
  'nba-27-2000': { name: "Duncan's Dynasty", description: "Tim Duncan and David Robinson win the title in Robinson's farewell season" },
  'nba-27-2005': { name: "Popovich's Best",  description: "Parker, Ginobili, and Duncan at their peak — the most complete team in the league" },
  // ── Heat ────────────────────────────────────────────────────────────────────
  'nba-16-2005': { name: 'D-Wade & Shaq',    description: "Dwyane Wade and Shaquille O'Neal deliver Miami's first NBA title" },
  'nba-16-2010': { name: "LeBron's Decision",description: "The Big Three — LeBron, Wade, and Bosh — win back-to-back championships" },
  // ── Warriors ────────────────────────────────────────────────────────────────
  'nba-10-2015': { name: 'Splash Brothers',  description: "Curry and Thompson light up the league; a 73-win season and three rings in four years" },
  'nba-10-2020': { name: 'Warriors Reloaded',description: "Steph Curry's scoring-title season and the 2022 championship keep Golden State's dynasty alive" },
  // ── Pistons ─────────────────────────────────────────────────────────────────
  'nba-9-1985':  { name: 'Bad Boys Rising',  description: "Isiah Thomas and the Bad Boys begin their bruising run toward a championship" },
  'nba-9-1990':  { name: 'Back-to-Back',     description: "Detroit's Bad Boys repeat as champions; the most physically dominant team of the era" },
  // ── 76ers ───────────────────────────────────────────────────────────────────
  'nba-23-1980': { name: 'Dr. J & Moses',    description: "Moses Malone joins Dr. J and declares 'Fo, Fo, Fo'; delivers the title in dominant fashion" },
  // ── Rockets ─────────────────────────────────────────────────────────────────
  'nba-11-1990': { name: "Hakeem's Rockets", description: "Hakeem Olajuwon's Dream Shake destroys defenses; back-to-back titles" },
  'nba-11-1995': { name: "Hakeem's Second",  description: "Hakeem leads Houston to a second straight title; one of the NBA's most underrated dynasties" },
  // ── Jazz ────────────────────────────────────────────────────────────────────
  'nba-29-1995': { name: 'Stockton & Malone',description: "The pick-and-roll duo reaches back-to-back Finals; the best team never to win it" },
  // ── Cavaliers ───────────────────────────────────────────────────────────────
  'nba-6-1985':  { name: 'Cavaliers Rising', description: "Cleveland builds around young talent; the foundation for future glory is laid" },
  'nba-6-1990':  { name: 'Mark Price Era',   description: "Mark Price and Brad Daugherty give Cleveland its most competitive pre-LeBron squad" },
  'nba-6-2005':  { name: "LeBron's First Act",description: "LeBron James carries a shorthanded Cavaliers squad to the Finals on pure will" },
  'nba-6-2015':  { name: 'LeBron Comes Home',description: "LeBron returns to Cleveland and delivers the city's first major title in 52 years" },
  // ── Nuggets ─────────────────────────────────────────────────────────────────
  'nba-8-2020':  { name: 'Jokic Era',        description: "Nikola Jokic wins three MVPs and leads Denver to its first championship" },
  // ── Bucks ───────────────────────────────────────────────────────────────────
  'nba-17-2020': { name: 'Greek Freak',      description: "Giannis Antetokounmpo wins two MVPs and a title in an all-time Bucks revival" },
  // ── Raptors ─────────────────────────────────────────────────────────────────
  'nba-28-2015': { name: 'We The North',     description: "Kawhi Leonard's iconic shot and Finals MVP give Canada its only NBA championship" },
  // ── Suns ────────────────────────────────────────────────────────────────────
  'nba-24-2005': { name: 'Seven Seconds',    description: "Steve Nash's two MVPs power the most exciting offense in basketball" },
  // ── Hawks ───────────────────────────────────────────────────────────────────
  'nba-1-1985':  { name: 'Dominique Era I',  description: "Dominique Wilkins emerges as one of the most electrifying scorers in the league" },
  'nba-1-1990':  { name: 'Dominique Era II', description: "The Human Highlight Film leads Atlanta to its best years; multiple 50-win seasons" },
  'nba-1-1995':  { name: 'Mutombo Era',      description: "Dikembe Mutombo anchors one of the NBA's elite defenses in the mid-90s" },
  'nba-1-2015':  { name: 'Hawks Renaissance',description: "The 60-win Hawks with five All-Stars show the NBA what team basketball looks like" },
  // ── Nets ────────────────────────────────────────────────────────────────────
  'nba-3-1990':  { name: 'Drazen Era',       description: "Drazen Petrovic and Kenny Anderson bring excitement to East Rutherford" },
  'nba-3-2000':  { name: 'Kidd Era',         description: "Jason Kidd leads New Jersey to back-to-back Finals; Kenyon Martin and K-Mart form a dangerous frontcourt" },
  'nba-3-2010':  { name: 'Brook Lopez Era',  description: "Brook Lopez carries the Nets franchise through a rebuilding period" },
  'nba-3-2015':  { name: 'Brooklyn Move',    description: "The Nets move to Brooklyn with massive stars; Harden era ends in a blockbuster run" },
  // ── Hornets ─────────────────────────────────────────────────────────────────
  'nba-4-1995':  { name: 'Mourning & Johnson',description: "Alonzo Mourning and Larry Johnson give Charlotte its most exciting era" },
  'nba-4-2000':  { name: 'Baron Davis Era',  description: "Baron Davis electrifies the league with highlight plays in Charlotte and New Orleans" },
  'nba-4-2010':  { name: 'Kemba Walker Era', description: "Kemba Walker becomes one of the East's elite guards, leading Charlotte's resurgence" },
};

export function generateTeamEras(team: HistoricalTeam): Era[] {
  const founded = TEAM_FOUNDED[`nba-${team.id}`] ?? NBA_ERA_START;
  const firstEraStart = Math.max(NBA_ERA_START, Math.floor(founded / 5) * 5);
  const eras: Era[] = [];

  for (let start = firstEraStart; start <= 2025; start += 5) {
    const id = `nba-${team.id}-${start}`;
    const custom = ERA_DATA[id];
    eras.push({
      id,
      teamId: team.id,
      sport: 'nba',
      startYear: start,
      endYear: start + 4,
      name: custom?.name ?? `${start}–${start + 4}`,
      description: custom?.description ?? `${team.city} ${team.name} — ${start}–${start + 4}`,
    });
  }

  return eras;
}
